### ISSUE TITLE
Upgrade to Backbone 0.5

### ISSUE THREAD

**Issue by kkaefer** [developmentseed/bones#17]

**Comment by lxbarth** [comment]
I just read through the diff between 0.3.3 and 0.5.1. These are the most important changes for upgrading Bones I'm seeing:
- Signature of sync() has changed - should be a straightforward adjustment, but it will touch many parts of our code.
- There are a series of changes to setLocation() (now `navigate()`) that will require rewriting our overrides for hash bangs.
- `Controller` is now `Router` - simple find and replace adjustment.

**Comment by lxbarth** [comment]
Per offline discussion with yhahn we'll want to hold on an upgrade of hashbang support for a first iteration.

Before investing further in hashbangs (or fragment support in general) we should seriously consider using pushState and a full-server fallback for browsers that don't support it.

**Comment by lxbarth** [comment]
I'll start working on this. I'll commit my work to master after branching 1.3. This upgrade will mean we need to go Bones 2.x.x as changes won't be backwards compatible.

**Comment by lxbarth** [comment]
I have made some good progress here today and committed my changes. All tests are completing and the example works fine, but I have not fully verified the upgrade yet. I'll keep this issue open until I have finalized porting the application I'm currently using Bones for.

**Comment by lxbarth** [comment]
This is done now. Work all committed to master branch.
