### ISSUE TITLE
Controller: Maintain backward compatibility

### ISSUE THREAD

**Issue by lxbarth** [developmentseed/bones#2]
kkaefer: I saw that the response() callback was lost in a recent refactor - I put it back in:

https://github.com/developmentseed/bones/commit/e5823e448c653a273a907fcb5db4b7adcb69bb4c

I saw that you did some refactoring work here and I wonder what the intentions of your refactoring work are here...

**Comment by kkaefer** [comment]
We threw that out on purpose; the res object is now an property of the controller's callback's context.
