### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by lxbarth** [developmentseed/bones#20]
After 0.5.x upgrade work was committed, what's missing for a 2.0 release?

https://github.com/developmentseed/bones/issues/17#issuecomment-1635601

**Comment by kkaefer** [comment]
I can't really think of anything in particular; if bones 2 works fine in a couple of projects, I'd say we should just go ahead and release a 2.0.0. If we don't want to be that bold, we can also do a bones 2.0.0alpha, similar to how tilemill alpha is now in npm.

**Comment by miccolis** [comment]
This happened a while ago see http://search.npmjs.org/#/bones
