### ISSUE TITLE
'require' needs to be available on the client to enable code reuse

### ISSUE THREAD

**Issue by Morriz** [developmentseed/bones#24]
I assumed require.js would be included in this module. Without it the server side code just won't be reusable I think.

As a matter of fact, I think the 'browserify' module should be used, to enable reuse of the 'templates' array on the client.

**Comment by tmcw** [comment]
This module uses mirror and `.server.bones` versus `.bones` files for the server/client side split - browserify and the require.js modules are a different approach and better for a non-framework approach, but they aren't in the same vein.
