### ISSUE TITLE
bones 2.x doesn't support this.$

### ISSUE THREAD

**Issue by tmcw** [developmentseed/bones#27]
These lines should be equivalent in Backbone:

``` javascript
this.$('.share-embed'); 
$('.share-embed', this.el);
```

But the `this.$` form fails with https://gist.github.com/1134286

**Comment by AdrianRossouw** [comment]
this works in [my fork](https://github.com/EmbarkSystems/bones)

the recommended way it to use the `this.$el` cached jquery element tho.

**Comment by lxbarth** [comment]
@Vertice - is there a patch/pull request for this?

**Comment by AdrianRossouw** [comment]
i can make one, but there's a whole bunch of changes (new underscore, new backbone, new jquery) that kind of build on each other.
