### ISSUE TITLE
Routers not sent to client

### ISSUE THREAD

**Issue by robotastic** [developmentseed/bones#31]
I am using the 2.0.0 branch of Bones. If I have routers names: Default.bones & Default.server.bones, Default.bones does not get sent to the client, routers.js is an empty file. If I remove the server version, Default.bones gets passed in the router.js file. If I rename Default.server.bones to Other.server.bones, Default.bones gets executed on the server and passed to the client. How do I execute separate Routers on the server and client?

**Comment by AdrianRossouw** [comment]
i don't know if you saw this example, but here you go : https://github.com/developmentseed/bones/tree/master/examples/simple/routers
