### ISSUE TITLE
node v0.6 fails

### ISSUE THREAD

**Issue by springmeyer** [developmentseed/bones#36]
Express 3.x (currently master) is required for node v.06 it appears.

Express 3.x removed its global `HTTPServer` so the usage of:

```
var HTTPServer = require('express').HTTPServer;
```

so `bones/server.js` fails:

```
~/projects/tilemill-node-v6[node-v6]$ ./index.js 
The "sys" module is now called "util". It should have a similar interface.

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Users/dane/projects/tilemill-node-v6/node_modules/bones/server/server.js:14:40)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/Users/dane/projects/tilemill-node-v6/node_modules/bones/bones.js:20:18)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
```

**Comment by springmeyer** [comment]
what was removed was https://github.com/visionmedia/express/blob/2.x/lib/express.js#L13 and now its just: https://github.com/visionmedia/express/blob/master/lib/express.js#L12

**Comment by AdrianRossouw** [comment]
when propping up a new project, the first issue i run into is that bones pins express at v2.4.4 , which only supports node v0.4.1 -> v0.5.x in it's package.json. 

this means that npm install fails on node 0.6.

**Comment by springmeyer** [comment]
@Vertice, right, I don't have privs to this repo, so I fixed that in a fork before going any further: https://github.com/springmeyer/bones/compare/master...node-v6

**Comment by springmeyer** [comment]
tests also fail with:

<img src="http://f.cl.ly/items/0a0T2Z2C3n1z0c0h2201/Screen%20Shot%202011-12-23%20at%203.32.59%20PM.png" />

**Comment by springmeyer** [comment]
hmm, sorry the above is not windows specific, likely occuring because I'm trying to run the tests from within a bone dir that npm installed and the `node_modules` has been stripped entirely.

**Comment by springmeyer** [comment]
all tests are now passing against express 2.5.4. new issue to track any issues at #47, closing this one.
