### ISSUE TITLE
How to use bones without node?

### ISSUE THREAD

**Issue by cnkt** [developmentseed/bones#40]
Anyone knows how can i use bones as standalone js for my html pages? the functions like require() etc. does not work because i want to run it in a browser.

**Comment by tmcw** [comment]
Hey @cnkt: the functionality of bones mainly lies in working with expressjs and server side code - if you just want write a client side app, use [Backbone](http://documentcloud.github.com/backbone/) directly.

**Comment by cnkt** [comment]
thanks for the info. @tmcw
