### ISSUE TITLE
Can not set config in Server plugin.

### ISSUE THREAD

**Issue by jackey** [developmentseed/bones#50]
using .augment() to override server/Router.bones initialize function and set this.enable('jsonp callback'), but it doesn't work.

I checked express code and found it use res.app.enabled('jsonp callback').

So, my issue is  Bones can not set config in server plugin to http server.

**Comment by makara** [comment]
In your server you need a middleware:

```
this.use(myMiddleware);
```

And in your middleware you can use `res.app.enable('jsonp callback');`.

Developmentseed, please close.
