### ISSUE TITLE
Create a 2.0 branch

### ISSUE THREAD

**Issue by makara** [developmentseed/bones#51]
Hi,

I don't think 2.1.x can be ready until https://github.com/developmentseed/mirror/issues/3 is solved (let me know if I'm wrong).

Would you consider creating a `2.0` branch so we can submit some pull requests?

Thanks.

**Comment by AdrianRossouw** [comment]
we consider master the 2.x branch.

there wasnt a 2.0 final release either, so you should just make all your pull requests against head.

I've applied your fixes to my branch btw, and they work well.

**Comment by makara** [comment]
2.1.x is working as a fork. Closing.
