### ISSUE TITLE
Share models and resources between processes

### ISSUE THREAD

**Issue by zbal** [developmentseed/bones#52]
Is there any way to share the models and current resources between different running processes of a same project? 

The example would be: 
- start a bones app with the "start" command 
- in a separate terminal run a "cli" command (as defined in the /commands/ folder)

The goal would be to access through the CLI to the objects defined and running already via the start command. It seems not to be possible currently. Would you have any input on that part?

Some of the options I'd imagine is to execute the CLI command and get it to connect as a client (a la mysql) to a defined API allowing it to fetch some of the resources and get the CLI to process and the results.

Any insights would be appreciated.

**Comment by lxbarth** [comment]
Models should only live for the time of a request, otherwise you'll wind up needing exactly what you're asking for - sharing them across processes :) My recommendation: don't go there.

Closing?

Reopen if I'm missing something important here.

**Comment by zbal** [comment]
That make perfect sense, we updated our code to ensure the models are only used on a per request basis, and opted for an extra API to interact with other features. Thanks.
