### ISSUE TITLE
Always send a hash with a key 'error' containing a string on errors

### ISSUE THREAD

**Issue by lxbarth** [developmentseed/bones#6]
Let me know what you think of this change. 

I was not quite clear why sometimes next() was called and sometimes an error was sent by `req.send()`.

The test for whether `err` is an Object is designed to ensure we're sending actually a string. This plays particularly well when `err` is an `Error` object (converts to the string that was passed in on construction).

https://github.com/developmentseed/bones/commit/46a202694ddd92cb02184d93c94d006b09247aed

**Comment by lxbarth** [comment]
Needs more work. In an offline discussion with kkaefer and yhahn we decided to standardize on an error object of the format 

```
{
    'message': 'Message string'
}
```

as this will be in line with JS' native `Error` object.

**Comment by yhahn** [comment]
Also, this will affect any client-side code that returns errors, e.g. `Model#validate()`.

**Comment by kkaefer** [comment]
This is done across all modules. Use `next(Error.HTTP(418))` or `next(Error.HTTP('toot toot', 418))` to send errors to the JSON error handler.
