### ISSUE TITLE
Consider changing `bones` suffix

### ISSUE THREAD

**Issue by miccolis** [developmentseed/bones#60]
I hate to bring this up, but I suspect we will be better off if we get our `.bones` suffixed files back into `.js` land. I've been using [jscoverage](https://github.com/visionmedia/node-jscoverage) on a bones project and I've had to hack it to instrument bones files. The change in the patch is very short but I think indicative of a class of problems that our custom file extension can create.

<pre>
-  if (string_ends_with(file, ".js")) {
+  if (string_ends_with(file, ".js") || string_ends_with(file, ".bones")) {
</pre>

**Comment by yhahn** [comment]
Hrm, quick tests indicate we could switch the `require.extensions` declaration from `.bones => .bones.js`.

Maybe for bones 3?

**Comment by kkaefer** [comment]
I like `.bones.js`

**Comment by AdrianRossouw** [comment]
indeed. and jshint/jslint will start working again

**Comment by miccolis** [comment]
The changes to make this possible aren't quite as clean as I'd like, see https://github.com/developmentseed/bones/commit/4c9ad45daa3a85427f698de1aabbc2233d277e05#L2R38

However I think it's tolerable. If there is consensus that this looks good I'll add a couple more tests that check that all private routers and view (in addition to the models where are tested) don't end up client site, and update the example.

**Comment by miccolis** [comment]
Let's move the conversation over to the pull request #61
