### ISSUE TITLE
Return model.attributes instead of resp in Route server middleware

### ISSUE THREAD

**Issue by willwhite** [developmentseed/bones#72]
On [this line](https://github.com/developmentseed/bones/blob/master/servers/Route.bones.js#L126) (and in other spots in the Route server), I'm trying to recall if we return `resp` instead of `model.attributes` for a reason. To me, It would make more sense to return the attributes since they have been parsed and validated and represent the model's true state on the server.

/cc @yhahn

**Comment by yhahn** [comment]
I can see this going either way -- basically:
1. If you think the model code / behavior should be _as similar as possible_ between the server/client then you would return `resp`,
2. If you think the model code / behavior can deviate aggressively between server/client then you would return `model.attributes` (by assuming the server will be doing work that the model on the client does not have logic/access to do).

I personally prefer the approach of #1 -- if you're using the same model namespace on server/client I would expect as close behavior as possible (e.g. you can instantiate from the same JSON).
